---
title: "Conda Lesson Setup"
format: html
order: 4
---

## Install `conda`

The conda lesson needs `conda` to be installed. There are several different ways to install `conda` (Anaconda, Miniconda, Miniforge); we will use [Miniconda](https://www.anaconda.com/docs/getting-started/miniconda/main). To install, do the following:

::: {.callout-note}
To install `conda` you'll first need a shell installed. If you haven't done it yet, install a shell following the instructions [here](00-setup.qmd).
:::

### Mac/Linux/Windows Subsystem for Linux (WSL)

1.  Open your terminal application and `cd` into your home directory by typing:

    ```bash
    cd
    ```

2.  Follow the instructions [Quickstart install instructions](https://www.anaconda.com/docs/getting-started/miniconda/install#quickstart-install-instructions) on the Miniconda website. For WSL, select "Linux".


### Windows

1. Download the [Miniconda installer for Windows](https://www.anaconda.com/download/success).
2. Run the installer by double-clicking on the downloaded file and follow the steps below.

   - Click “Run”.
   - Click on “Next”.
   - Click on “I agree”.
   - Select “Just me” and click on “Next”.
   - Click on “Next”.
   - Check the option for “Add Anaconda to my PATH environment variable” and check the option for “Register Anaconda as my default Python 3.12”.
     - Note that even though the installation is for Miniconda, the installer uses the word Anaconda in these options.
     - You will also see a message in red text that selecting “Add Anaconda to my PATH environment variable” is not recommended; continue with this selection to make using conda easier in Git Bash. If you have questions or concerns, please contact your instructor.
   - Click on “Install”.
   - When the install is complete, Click on “Next”.
   - Click on “Finish”.

3. Open a new Git Bash window and type the following command to initialize conda:

    ```bash
    conda init bash
    ```

## Verify the installation

Once the installation is done, open a new terminal window (Terminal on Mac/Linux, WSL or Git Bash on Windows) for the installation to take effect. If you see "(base)", then Miniconda has been installed properly.

