---
title: "Computing 101 Workshop – Summer 2025"
subtitle: "Introduction to GitHub, Programming with Python/R, and Reproducible Environments with Bash and Conda"
toc: true
---

**August 13-15, 2025**

[Hinds Hall, Syracuse University](https://maps.app.goo.gl/x9dpAmJCGJ5RemUVA)

# Welcome

This 3-day workshop will cover some of the common tools used in open source development. It is targeted at novice users. The workshop will be broken into three parts:

 - **Programming basics (day 1)** – Topics covered: intro to R/Python, git and GitHub.
 - **Advancing programming (day 2)** – Topics covered:  data cleaning (R), data visualization (R/Python), loops and classes (Python), miscellaneous advanced topics (Python).
 - **(optional) Reproducible environments (day 3)** – Topics covered: bash environments, package managers (e.g., conda).

## Schedule

| Date                | Time                | Location  | Topic                                                                                    | Presenter       |
|:-------------------:|:-------------------:|:---------:|:----------------------------------------------------------------------------------------:|:---------------:|
| Wednesday, August 13| 9:00 AM - 10:00 AM  | Hinds 111 | Optional: [Software Setup Help](#installation)                                           |                 |
| Wednesday, August 13| 10:00 AM - 12:00 PM | Hinds 111 | [Intro to Python](02_python/python-intro.qmd)                                            | TBA             |
| Wednesday, August 13| 10:00 AM - 12:00 PM | Hinds 117 | [Intro to R: variables and functions](01_r/r-intro.qmd)                                  | Sarah Lucas     |
| Wednesday, August 13| 2:00 PM - 4:00 PM   | Hinds 111 | [`git` and GitHub](03_github/index.qmd)                                                  | Collin Capano   |
| Thursday, August 14 | 10:00 AM - 12:00 PM | Hinds 111 | [Advanced Python: flow, loops, and classes](02_python/python-flow.qmd)                   | TBA             |
| Thursday, August 14 | 10:00 AM - 12:00 PM | Hinds 117 | [Advanced R: data cleaning with the tidyverse](01_r/r-tidydata.qmd)                      | Jessie Trudeau  |
| Thursday, August 14 | 2:00 PM - 4:00 PM   | Hinds 111 | [Advanced Python: miscellaneous applications](02_python/python-apps.qmd)                 | TBA             |
| Thursday, August 14 | 2:00 PM - 4:00 PM   | Hinds 117 | [Advanced R: data vizualization with ggplot2](01_r/r-plotting.qmd)                       | Will Gearty     |
| Friday, August 15   | 10:00 AM - 12:00 PM | Hinds 111 | Bash and Conda                                                                           | Collin Capano   |
| Friday, August 15   | 2:00 PM - 4:00 PM   | Hinds 111 | Bash and Conda (cont.)                                                                   | Collin Capano   |

## Installation

**Attendees should install the following software before the workshop:**

- [GitHub Desktop](https://desktop.github.com/download/) (and make a GitHub account if you don't have one already)
- [Miniconda](https://www.anaconda.com/docs/getting-started/miniconda/install) (if attending Python sessions)
- [R](https://cloud.r-project.org/) and [RStudio](https://posit.co/download/rstudio-desktop/) (if attending R sessions)
